export const BUTTONS_PARAMS = [
    { title: 'AC', className: 'dark' },
    { title: '+/-', className: 'dark' },
    { title: '%', className: 'dark' },
    { title: '/', className: 'orange' },
    { title: '7', className: 'light' },
    { title: '8', className: 'light' },
    { title: '9', className: 'light' },
    { title: 'X', className: 'orange' },
    { title: '4', className: 'light' },
    { title: '5', className: 'light' },
    { title: '6', className: 'light' },
    { title: '-', className: 'orange' },
    { title: '1', className: 'light' },
    { title: '2', className: 'light' },
    { title: '3', className: 'light' },
    { title: '+', className: 'orange' },
    { title: '0', className: 'btn-zero' },
    { title: ',', className: 'light' },
    { title: '=', className: 'orange' },
  ];