export const BUTTONS_PARAMS = [
  { type: 'clear', title: 'AC', className: 'dark' },
  { type: 'sign', title: '+/-', className: 'dark' },
  { type: 'percent', title: '%', className: 'dark' },
  { type: 'operator', title: '/', className: 'orange' },
  { type: 'number', title: '7', className: 'light' },
  { type: 'number', title: '8', className: 'light' },
  { type: 'number', title: '9', className: 'light' },
  { type: 'operator', title: '×', className: 'orange' },
  { type: 'number', title: '4', className: 'light' },
  { type: 'number', title: '5', className: 'light' },
  { type: 'number', title: '6', className: 'light' },
  { type: 'operator', title: '-', className: 'orange' },
  { type: 'number', title: '1', className: 'light' },
  { type: 'number', title: '2', className: 'light' },
  { type: 'number', title: '3', className: 'light' },
  { type: 'operator', title: '+', className: 'orange' },
  { type: 'number', title: '0', className: 'btn-zero' },
  { type: 'comma', title: ',', className: 'light' },
  { type: 'equal', title: '=', className: 'orange' },
] as const;
